import { Building, Vehicle, Animal, Insect, NPC, QuestStep, PlayerState } from '../types/game';

export const WORLD_WIDTH = 2400;
export const WORLD_HEIGHT = 1800;

export const INITIAL_PLAYER: PlayerState = {
  x: 1160,
  y: 860,
  speed: 4,
  facing: 'down',
  role: 'mailman', // starting role
  inVehicleId: null,
  coins: 45,
  bag: {
    letters: 6,
    packages: 3,
    dogTreats: 5,
    catTreats: 5,
    bugNet: true,
    magnifyingGlass: true,
    pastry: 1,
  },
  reputation: 100,
};

export const BUILDINGS: Building[] = [
  // 1. STORES
  {
    id: 'store_grocery',
    name: 'Sunnyvale Supermarket & Grocer',
    type: 'store',
    subtype: 'grocery',
    x: 1350,
    y: 620,
    width: 220,
    height: 140,
    color: '#34d399',
    roofColor: '#059669',
    doorPos: { x: 1460, y: 760 },
    description: 'Fresh local produce, crisp apples, pet treats, and cold drinks.',
  },
  {
    id: 'store_bakery',
    name: 'Honeycomb Bakery & Cafe',
    type: 'store',
    subtype: 'bakery',
    x: 1620,
    y: 620,
    width: 180,
    height: 140,
    color: '#fbbf24',
    roofColor: '#d97706',
    doorPos: { x: 1710, y: 760 },
    description: 'Golden croissants, warm sourdough, cinnamon buns, and espresso.',
  },
  {
    id: 'store_toys',
    name: 'WonderBug Toy & Hobby Shop',
    type: 'store',
    subtype: 'toy_shop',
    x: 1840,
    y: 620,
    width: 190,
    height: 140,
    color: '#f472b6',
    roofColor: '#db2777',
    doorPos: { x: 1935, y: 760 },
    description: 'Bug-catching nets, magnifying glasses, dog balls, and model planes.',
  },
  {
    id: 'store_pharmacy',
    name: 'Corner Care Pharmacy',
    type: 'store',
    subtype: 'pharmacy',
    x: 1350,
    y: 960,
    width: 180,
    height: 130,
    color: '#38bdf8',
    roofColor: '#0284c7',
    doorPos: { x: 1440, y: 960 },
    description: 'First-aid kits, soothing ointments, bandages, and wellness vitamins.',
  },

  // 2. SCHOOLS
  {
    id: 'school_main',
    name: 'Sunnyvale Elementary & Academy',
    type: 'school',
    x: 1600,
    y: 120,
    width: 380,
    height: 220,
    color: '#e0e7ff',
    roofColor: '#4338ca',
    doorPos: { x: 1790, y: 340 },
    description: 'Bustling classrooms, library, school bus bay, and cheerful recess playground with basketball hoop.',
  },

  // 3. CHURCHES
  {
    id: 'church_grace',
    name: "Grace Community Chapel & Bell Tower",
    type: 'church',
    x: 320,
    y: 980,
    width: 280,
    height: 240,
    color: '#fef08a',
    roofColor: '#ca8a04',
    doorPos: { x: 460, y: 980 },
    description: 'Historic stone chapel with soaring bell tower, stained glass windows, serene garden fountain, and ancient oak tree.',
  },

  // 4. CIVIC & EMERGENCY BUILDINGS
  {
    id: 'station_police',
    name: 'Sunnyvale Police Precinct 4',
    type: 'police_station',
    x: 320,
    y: 580,
    width: 250,
    height: 160,
    color: '#93c5fd',
    roofColor: '#1d4ed8',
    doorPos: { x: 445, y: 740 },
    description: 'Headquarters for neighborhood safety, patrol cruiser garage, radio dispatch, and safe-walker badges.',
  },
  {
    id: 'station_fire',
    name: 'Engine Company Fire Station 7',
    type: 'fire_station',
    x: 620,
    y: 580,
    width: 240,
    height: 160,
    color: '#fca5a5',
    roofColor: '#b91c1c',
    doorPos: { x: 740, y: 740 },
    description: 'Fire Engine Ladder 4 bay, water hydrants, rescue gear, and high-altitude cat rescue ladder.',
  },
  {
    id: 'hospital_clinic',
    name: 'Sunnyvale Emergency Medical Center',
    type: 'hospital',
    x: 890,
    y: 580,
    width: 170,
    height: 160,
    color: '#f1f5f9',
    roofColor: '#ef4444',
    doorPos: { x: 975, y: 740 },
    description: 'Paramedic ambulance bay, emergency care doctors, and health response team.',
  },

  // 5. NEIGHBORHOOD HOMES (HOUSES)
  {
    id: 'house_1',
    name: '101 Oak Street',
    type: 'house',
    x: 280,
    y: 120,
    width: 180,
    height: 130,
    color: '#fed7aa',
    roofColor: '#c2410c',
    doorPos: { x: 370, y: 250 },
    mailboxPos: { x: 370, y: 270 },
    residentName: 'The Miller Family',
    addressNumber: 101,
    hasMailFlag: true,
    hasDeliveredMail: false,
    description: 'Cozy cottage with rose bushes. Buster the golden retriever lives here!',
  },
  {
    id: 'house_2',
    name: '103 Oak Street',
    type: 'house',
    x: 520,
    y: 120,
    width: 190,
    height: 130,
    color: '#dcfce7',
    roofColor: '#15803d',
    doorPos: { x: 615, y: 250 },
    mailboxPos: { x: 615, y: 270 },
    residentName: 'The Chen Residence',
    addressNumber: 103,
    hasMailFlag: true,
    hasDeliveredMail: false,
    description: 'Charming house with cherry blossom tree and wind chimes.',
  },
  {
    id: 'house_3',
    name: '105 Oak Street',
    type: 'house',
    x: 770,
    y: 120,
    width: 180,
    height: 130,
    color: '#fef3c7',
    roofColor: '#b45309',
    doorPos: { x: 860, y: 250 },
    mailboxPos: { x: 860, y: 270 },
    residentName: "Grandma Helen's Porch",
    addressNumber: 105,
    hasMailFlag: true,
    hasDeliveredMail: false,
    description: 'Porch rocking chairs, bird feeder, and Daisy the corgi enjoying the sun.',
  },
  {
    id: 'house_4',
    name: '202 Maple Lane',
    type: 'house',
    x: 1350,
    y: 1240,
    width: 190,
    height: 130,
    color: '#fae8ff',
    roofColor: '#86198f',
    doorPos: { x: 1445, y: 1370 },
    mailboxPos: { x: 1445, y: 1390 },
    residentName: 'The Baker Residence',
    addressNumber: 202,
    hasMailFlag: true,
    hasDeliveredMail: false,
    description: 'Sunny bungalow with tomato plants and hanging flower pots.',
  },
  {
    id: 'house_5',
    name: '204 Maple Lane',
    type: 'house',
    x: 1610,
    y: 1240,
    width: 190,
    height: 130,
    color: '#ffe4e6',
    roofColor: '#be123c',
    doorPos: { x: 1705, y: 1370 },
    mailboxPos: { x: 1705, y: 1390 },
    residentName: 'The Rodriguez Villa',
    addressNumber: 204,
    hasMailFlag: true,
    hasDeliveredMail: false,
    description: 'Spanish tile roof, terracotta planters, and outdoor barbecue patio.',
  },
  {
    id: 'house_6',
    name: '206 Maple Lane',
    type: 'house',
    x: 1860,
    y: 1240,
    width: 180,
    height: 130,
    color: '#e0f2fe',
    roofColor: '#0369a1',
    doorPos: { x: 1950, y: 1370 },
    mailboxPos: { x: 1950, y: 1390 },
    residentName: 'The Garden House',
    addressNumber: 206,
    hasMailFlag: true,
    hasDeliveredMail: false,
    description: 'Lush sunflower patch and garden hives where busy honeybees collect nectar.',
  },
];

export const VEHICLES: Vehicle[] = [
  {
    id: 'veh_police',
    name: 'Police Cruiser Unit 1',
    type: 'police_cruiser',
    x: 480,
    y: 780,
    angle: 0,
    speed: 0,
    color: '#1e3a8a',
    secondaryColor: '#ffffff',
    hasSiren: true,
    sirenActive: false,
    isDrivenByPlayer: false,
    width: 38,
    length: 64,
  },
  {
    id: 'veh_mail',
    name: 'USPS Postal Delivery Van',
    type: 'mail_truck',
    x: 1140,
    y: 840,
    angle: 0,
    speed: 0,
    color: '#ffffff',
    secondaryColor: '#2563eb',
    hasSiren: false,
    sirenActive: false,
    isDrivenByPlayer: false,
    width: 38,
    length: 66,
  },
  {
    id: 'veh_fire',
    name: 'Fire Engine Ladder 4',
    type: 'fire_truck',
    x: 770,
    y: 780,
    angle: 0,
    speed: 0,
    color: '#dc2626',
    secondaryColor: '#fef08a',
    hasSiren: true,
    sirenActive: false,
    isDrivenByPlayer: false,
    width: 44,
    length: 80,
  },
  {
    id: 'veh_ambulance',
    name: 'Paramedic Ambulance 9',
    type: 'ambulance',
    x: 990,
    y: 780,
    angle: 0,
    speed: 0,
    color: '#f8fafc',
    secondaryColor: '#ef4444',
    hasSiren: true,
    sirenActive: false,
    isDrivenByPlayer: false,
    width: 40,
    length: 70,
  },
  {
    id: 'veh_bicycle',
    name: "Explorer's Blue Cruiser Bike",
    type: 'bicycle',
    x: 1080,
    y: 870,
    angle: 0,
    speed: 0,
    color: '#0284c7',
    secondaryColor: '#38bdf8',
    hasSiren: false,
    sirenActive: false,
    isDrivenByPlayer: false,
    width: 20,
    length: 36,
  },
];

export const ANIMALS: Animal[] = [
  // CATS
  {
    id: 'cat_milo',
    name: 'Milo',
    species: 'cat',
    breed: 'Ginger Tabby',
    x: 620,
    y: 1180,
    targetX: 620,
    targetY: 1180,
    state: 'tree',
    color: '#ea580c',
    facing: 'left',
    friendliness: 90,
    favoriteToy: 'Feather wand & catnip mouse',
    isStuckInTree: true,
  },
  {
    id: 'cat_whiskers',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Tuxedo Cat',
    x: 1720,
    y: 780,
    targetX: 1740,
    targetY: 780,
    state: 'idle',
    color: '#1e293b',
    facing: 'right',
    friendliness: 85,
    favoriteToy: 'Yarn ball',
    isStuckInTree: false,
  },
  {
    id: 'cat_luna',
    name: 'Luna',
    species: 'cat',
    breed: 'Calico',
    x: 750,
    y: 1120,
    targetX: 790,
    targetY: 1140,
    state: 'walking',
    color: '#d97706',
    facing: 'left',
    friendliness: 95,
    favoriteToy: 'Laser pointer light',
    isStuckInTree: false,
  },

  // DOGS
  {
    id: 'dog_buster',
    name: 'Buster',
    species: 'dog',
    breed: 'Golden Retriever',
    x: 410,
    y: 290,
    targetX: 430,
    targetY: 310,
    state: 'playing',
    color: '#eab308',
    facing: 'right',
    friendliness: 100,
    favoriteToy: 'Tennis ball',
  },
  {
    id: 'dog_daisy',
    name: 'Daisy',
    species: 'dog',
    breed: 'Pembroke Welsh Corgi',
    x: 880,
    y: 290,
    targetX: 890,
    targetY: 280,
    state: 'idle',
    color: '#f97316',
    facing: 'left',
    friendliness: 90,
    favoriteToy: 'Squeaky plush duck',
  },
  {
    id: 'dog_rocky',
    name: 'Rocky',
    species: 'dog',
    breed: 'English Bulldog',
    x: 1470,
    y: 1410,
    targetX: 1470,
    targetY: 1410,
    state: 'sleeping',
    color: '#78716c',
    facing: 'right',
    friendliness: 80,
    favoriteToy: 'Rope chew knot',
  },
];

export const INSECTS: Insect[] = [
  {
    id: 'ins_monarch',
    name: 'Monarch Butterfly',
    species: 'butterfly',
    x: 1050,
    y: 1100,
    originX: 1050,
    originY: 1100,
    color: '#f97316',
    wingAngle: 0,
    caught: false,
    rarity: 'common',
    fact: 'Monarchs migrate thousands of miles and drink nectar from milkweed and zinnias.',
  },
  {
    id: 'ins_blue_morpho',
    name: 'Blue Morpho Butterfly',
    species: 'butterfly',
    x: 520,
    y: 1120,
    originX: 520,
    originY: 1120,
    color: '#0284c7',
    wingAngle: 0,
    caught: false,
    rarity: 'uncommon',
    fact: 'The brilliant blue sheen comes from tiny micro-scales reflecting sunlight!',
  },
  {
    id: 'ins_honeybee',
    name: 'Golden Honeybee',
    species: 'bee',
    x: 1960,
    y: 1420,
    originX: 1960,
    originY: 1420,
    color: '#facc15',
    wingAngle: 0,
    caught: false,
    rarity: 'common',
    fact: 'Honeybees communicate flower locations through an extraordinary waggle dance.',
  },
  {
    id: 'ins_bumblebee',
    name: 'Fuzzy Bumblebee',
    species: 'bee',
    x: 1720,
    y: 1410,
    originX: 1720,
    originY: 1410,
    color: '#eab308',
    wingAngle: 0,
    caught: false,
    rarity: 'common',
    fact: 'Bumblebees vibrate flowers with their wings to pollinate tomatoes and berries.',
  },
  {
    id: 'ins_ladybug',
    name: 'Seven-Spotted Ladybug',
    species: 'ladybug',
    x: 430,
    y: 270,
    originX: 430,
    originY: 270,
    color: '#ef4444',
    wingAngle: 0,
    caught: false,
    rarity: 'common',
    fact: 'Ladybugs are garden protectors, eating pest aphids to keep flowers healthy.',
  },
  {
    id: 'ins_dragonfly',
    name: 'Emerald Pond Dragonfly',
    species: 'dragonfly',
    x: 460,
    y: 1220,
    originX: 460,
    originY: 1220,
    color: '#10b981',
    wingAngle: 0,
    caught: false,
    rarity: 'uncommon',
    fact: 'Dragonflies can fly backwards, hover upside-down, and have 360-degree compound eyes.',
  },
  {
    id: 'ins_firefly',
    name: 'Twinkling Firefly',
    species: 'firefly',
    x: 780,
    y: 1180,
    originX: 780,
    originY: 1180,
    color: '#a3e635',
    glowColor: '#84cc16',
    wingAngle: 0,
    caught: false,
    rarity: 'rare',
    fact: 'Fireflies produce cold light via bioluminescence to glow beautifully in the evening.',
  },
];

export const NPCS: NPC[] = [
  {
    id: 'npc_officer_davis',
    name: 'Officer Davis',
    role: 'policeman',
    x: 420,
    y: 770,
    facing: 'right',
    activity: 'Patrolling neighborhood crosswalks & traffic',
    color: '#1e3a8a',
    hairColor: '#475569',
    dialog: [
      'Good day, neighbor! Sunnyvale is peaceful today.',
      'Always remember to look both ways at the zebra crosswalk!',
      'If you need safety escorts around school recess, call Unit 1 on radio.',
    ],
  },
  {
    id: 'npc_mailman_bob',
    name: 'Mail Carrier Bob',
    role: 'mailman',
    x: 1190,
    y: 840,
    facing: 'left',
    activity: 'Sorting letters and route manifests',
    color: '#2563eb',
    hairColor: '#92400e',
    dialog: [
      'Neither snow nor rain nor friendly dogs stops the mail!',
      'Buster loves greeting me at 101 Oak Street—always keep a dog treat handy.',
      'Help me deliver packages to the houses along Oak Street and Maple Lane!',
    ],
  },
  {
    id: 'npc_teacher_clara',
    name: 'Ms. Clara',
    role: 'teacher',
    x: 1780,
    y: 360,
    facing: 'down',
    activity: 'Supervising student recess and playground fun',
    color: '#7c3aed',
    hairColor: '#ca8a04',
    dialog: [
      'Welcome to Sunnyvale Academy! The school bell just rang for recess.',
      'Care to try shooting a free-throw at the basketball court?',
      'The children love learning about the butterflies in our science garden.',
    ],
  },
  {
    id: 'npc_pastor_john',
    name: 'Pastor John',
    role: 'pastor',
    x: 460,
    y: 950,
    facing: 'down',
    activity: 'Tending the church garden and bell tower',
    color: '#4b5563',
    hairColor: '#cbd5e1',
    dialog: [
      'Peace be with you, friend! The church bell welcomes all neighbors.',
      'Our oak tree is very tall. Sometimes little Milo the cat climbs up high!',
      'Take a moment to sit by the courtyard fountain and listen to the birds.',
    ],
  },
  {
    id: 'npc_baker_marcel',
    name: 'Baker Marcel',
    role: 'baker',
    x: 1710,
    y: 780,
    facing: 'down',
    activity: 'Baking fresh baguettes and cinnamon pastries',
    color: '#d97706',
    hairColor: '#78350f',
    dialog: [
      'Bonjour! Smells delicious, non? Cinnamon buns are warm out of the oven!',
      'Eating a pastry gives your legs an energizing boost of speed.',
      'Whiskers the cat loves napping on our warm flour sacks outside!',
    ],
  },
];

export const INITIAL_QUESTS: QuestStep[] = [
  {
    id: 'quest_mail',
    sectorName: 'Sector 1: Postal Service & Neighborhood Routes',
    title: 'Morning Mail & Parcel Delivery',
    targetRole: 'mailman',
    description: 'Deliver morning mail and packages to neighborhood homes. Check mailboxes with raised red flags!',
    instructions: 'Switch to Mail Carrier or board the Mail Truck. Walk up to at least 3 house mailboxes and press Deliver.',
    icon: 'mail',
    targetCount: 3,
    currentCount: 0,
    isReadyToConfirm: false,
    isCompleted: false,
    rewardText: 'Neighborhood Postal Star Badge & 25 Coins',
  },
  {
    id: 'quest_police',
    sectorName: 'Sector 2: Law Enforcement & School Safety',
    title: 'School Crossing Guard & Safe Patrol',
    targetRole: 'police',
    description: 'Protect the neighborhood! Patrol the school zone, assist pedestrians at the zebra crossing, and blow the safety whistle.',
    instructions: 'Switch to Police Officer or drive the Police Cruiser. Patrol the crosswalk outside Sunnyvale School and talk to Officer Davis or sound the siren.',
    icon: 'shield',
    targetCount: 2,
    currentCount: 0,
    isReadyToConfirm: false,
    isCompleted: false,
    rewardText: 'Honorary Officer Shield & 30 Coins',
  },
  {
    id: 'quest_emergency',
    sectorName: 'Sector 3: Emergency Dispatch & Rescue',
    title: 'Church Oak Tree Emergency Rescue',
    targetRole: 'firefighter',
    description: 'Dispatch call: Milo the orange cat is stuck high in the ancient oak tree beside Grace Church!',
    instructions: 'Drive the Fire Truck or Ambulance to Grace Church. Walk to the oak tree and deploy the rescue ladder to bring Milo down safely.',
    icon: 'flame',
    targetCount: 1,
    currentCount: 0,
    isReadyToConfirm: false,
    isCompleted: false,
    rewardText: 'First Responder Hero Medal & Milo Gratitude Purr',
  },
  {
    id: 'quest_store',
    sectorName: 'Sector 4: Downtown Commerce & Supplies',
    title: 'Corner Store & Bakery Shopping Spree',
    targetRole: 'explorer',
    description: 'Visit the neighborhood shops! Pick up fresh treats at Honeycomb Bakery and supplies at Sunnyvale Supermarket.',
    instructions: 'Enter Honeycomb Bakery and Sunnyvale Supermarket. Buy or inspect items from the shopkeepers.',
    icon: 'shopping-bag',
    targetCount: 2,
    currentCount: 0,
    isReadyToConfirm: false,
    isCompleted: false,
    rewardText: 'Local Patron Ribbon & Delicious Cinnamon Bun',
  },
  {
    id: 'quest_pets',
    sectorName: 'Sector 5: Furry Companions & Pet Care',
    title: 'Neighborhood Pets Happiness Tour',
    targetRole: 'explorer',
    description: 'Befriend the friendly neighborhood dogs and cats. Give them pets, treats, or play fetch with Buster!',
    instructions: 'Approach Buster, Daisy, Rocky, or Whiskers. Interact to pet them, feed dog biscuits, or toss a ball.',
    icon: 'heart',
    targetCount: 3,
    currentCount: 0,
    isReadyToConfirm: false,
    isCompleted: false,
    rewardText: 'Master Animal Whisperer Badge & 35 Coins',
  },
  {
    id: 'quest_insects',
    sectorName: 'Sector 6: Backyard Biodiversity & Entomology',
    title: 'Neighborhood Insect & Butterfly Safari',
    targetRole: 'explorer',
    description: 'Observe and document local insects fluttering in gardens, rose bushes, and the church fountain.',
    instructions: 'Equip your bug net or magnifying glass. Approach butterflies, bees, ladybugs, or dragonflies to record them into your Field Guide.',
    icon: 'bug',
    targetCount: 3,
    currentCount: 0,
    isReadyToConfirm: false,
    isCompleted: false,
    rewardText: 'Junior Entomologist Trophy & Complete Field Guide',
  },
];
